export const Chapters: string[] = [
  "01. Imaginate!",
  "02. The Game",
  "03. Cat Tail",
  "04. The Raccoons",
  "05. The Adventures of Spot",
  "06. Fido's Return",
  "07. Mouse Mouse Revolution",
  "08. Thematic Arc of Questionable Quality",
  "09. The Zoo",
  "10. The Grove",
  "11. Housepets Christmas",
  "12. The Yarn Ball",
  "13. The Further Adventures of Spot",
  "14. The Vet",
  "15. A Mouse Named Spo",
  "16. Zap!",
  "17. Fail of the Pridelands",
  "18. The Continuing Adventures of Spot",
  "19. A Sinister Shadow",
  "20. Roadtrip Woo"
]
