import AppHeader from "./AppHeader"
import AppFooter from "./AppFooter"
import Head from "next/head"
import React from "react"

export default function Layout({ children }: any) {
  return(
    <>
      <Head>
        <title>Housepets Search Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        {children}
      </main>
      <AppFooter />
    </>
  )
}